Parameters:
  VpcCidrBlock:
    Type: String
    Description: Cidr block of the Vpc
    Default: "10.10.0.0/16"
  SubnetCidrBlock:
    Type: String
    Description: Cidr block of the Subnet
    Default: "10.10.0.0/24"

Mappings:
  EnvTypeMap:
    ap-southeast-2:
      environment: "dev"
    us-east-1:
      environment: "prod"

Resources:
  Vpc:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock:
        Ref: VpcCidrBlock
      EnableDnsHostnames: True
      EnableDnsSupport: True
      Tags:
        - Key: "Name"
          Value:
            !Join
              - "-"
              - - !FindInMap
                  - EnvTypeMap
                  - Ref: AWS::Region
                  - environment
                - Ref: AWS::StackName
                - "vpc"
        - Key: "Environment"
          Value: !FindInMap
            - EnvTypeMap
            - Ref: AWS::Region
            - environment

  Subnet:
    Type: AWS::EC2::Subnet
    Properties:
      CidrBlock:
        Ref: SubnetCidrBlock
      MapPublicIpOnLaunch: true
      VpcId:
        Ref: Vpc
      Tags:
        - Key: "Name"
          Value:
            !Join
              - "-"
              - - !FindInMap
                  - EnvTypeMap
                  - Ref: AWS::Region
                  - environment
                - Ref: AWS::StackName
                - "subnet"