name: Create CloudFormation stack.

on: push

permissions:
  id-token: write
  contents: read

jobs:
  create_stack:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: aws authentication
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ap-southeast-2
      
      - name: run aws cli commands
        run: aws s3 cp /home/runner/work/fraedo-cf/fraedo-cf/ s3://fraedo-bucket --recursive --exclude "LICENSE" --exclude "*.md" --exclude ".git/*"

      - name: create cf stack
        id: create_stack
        run: |
          STACKNAME="cf-${{ github.run_number }}"
          aws cloudformation create-stack --stack-name $STACKNAME --template-body file://0-root-stack.yaml
          sleep 300

      - name: delete cf stack
        if: steps.create_stack.outcome == 'success'
        run: aws cloudformation delete-stack --stack-name $STACKNAME
